### PR TITLE
Use zig for benchmarking

### LINKED ISSUE #4: Benchmarking with zig
Hi,

Using hyperfine for benchmarking is OK, but in my opinion it would be much better to use a zig implementation. I am not saying that I will even write the graph part, but the bechmarking and outputting to json seems manageable.

Are You interested in such contributions? I would only start it if You are open for this.

Thanks,

### PR DESCRIPTION
**Pull request by voroskoi**
Closes #4 

For now generating JSON data from zig works. I have not tested the python chart drawing yet.

What about using mermaid syntax for showing benchmark results instead of python?

### CODE REVIEW

**Comment by alichraghi** [comment]
Very nice!
when writing that i didn't know anything about python, and as u can see it's buggy. so it's good to hear **mermaid** exists.
i think this can merged now and then add you as collaborator
what do you think?

**Comment by voroskoi** [comment]
Hi,

OK, this is the initial working version. What do You think?

**Comment by alichraghi** [comment]
amazing!

**Comment by voroskoi** [comment]
Glad You like it. And thanks for having me as a collaborator :-)

**Pull request merged**
